<Project Sdk="Aspire.AppHost.Sdk/13.5.1">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>335e9492-fd9d-4d1b-bf11-79ad226fcf2e</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\OnlineConsulting.Api\OnlineConsulting.Api.csproj" />
    <ProjectReference Include="..\OnlineConsulting.UserInterface\OnlineConsulting.UserInterface.csproj" />
  </ItemGroup>

</Project>
