<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Core.ApplicationLayer" />
    <PackageReference Include="Core.PersistenceLayer" />
    <PackageReference Include="Core.SecurityLayer" />
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" />
    <PackageReference Include="MediatR" />
    <PackageReference Include="ResponseResultHandler" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" />
  </ItemGroup>

</Project>
