<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Core.ApplicationLayer" />
    <PackageReference Include="Core.PersistenceLayer" />
    <PackageReference Include="Core.SecurityLayer" />
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="Hateoas" />
    <PackageReference Include="MediatR" />
    <PackageReference Include="ResponseResultHandler" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\OnlineConsulting.Modules.Identity.Domain\OnlineConsulting.Modules.Identity.Domain.csproj" />
    <ProjectReference Include="..\..\..\OnlineConsulting.SharedKernel\OnlineConsulting.SharedKernel.csproj" />
  </ItemGroup>

</Project>
