<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Core.ApplicationLayer" Version="[1.0.23-beta.23]" />
    <PackageReference Include="Core.PersistenceLayer" Version="[1.0.23-beta.23]" />
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="MediatR" Version="14.2.0" />
    <PackageReference Include="ResponseResultHandler" Version="12.0.0-beta.26" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\OnlineConsulting.Modules.Media.Domain\OnlineConsulting.Modules.Media.Domain.csproj" />
    <ProjectReference Include="..\..\..\OnlineConsulting.SharedKernel\OnlineConsulting.SharedKernel.csproj" />
  </ItemGroup>

</Project>
